/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/UI/AppButton.vue')['default']
    AppCard: typeof import('./src/components/UI/AppCard.vue')['default']
    AppCheckbox: typeof import('./src/components/UI/AppCheckbox.vue')['default']
    AppIcon: typeof import('./src/components/UI/AppIcon.vue')['default']
    AppInput: typeof import('./src/components/UI/AppInput.vue')['default']
    AppList: typeof import('./src/components/UI/AppList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
